Solr request tests
mpi2/impc-data-api-workshop pull request #10
Opened 2024-08-22 09:36 UTC by dpavam

Adds basic test suite of the solr_request function

2024-08-23 09:57 UTC, marinak-ebi commented on impc_api_helper/tests/test_solr_request.py
> +    def test_successful_request(sef, mock_response, core, common_params):
Probably small typo and should be `self` instead of `sef`

2024-08-23 10:00 UTC, marinak-ebi commented on impc_api_helper/tests/test_solr_request.py
> +    def test_solr_request_error(self, mock_response, core, common_params):
I suggest to rename `test_solr_request_error ` to `test_unsuccessful_request` for consistency with other test method names.

2024-08-23 10:10 UTC, dpavam commented on impc_api_helper/tests/test_solr_request.py
> +    def test_solr_request_error(self, mock_response, core, common_params):
Well spotted. Would something like this be better to distinguish between normal requests and facet ?: 
- `test_successful_solr_request`, 
- `test_unsuccessful_solr_request`, 
- `test_successful_facet_request`, 
- `test_unsuccessful_facet_request`.

2024-08-23 10:11 UTC, marinak-ebi commented on impc_api_helper/tests/test_solr_request.py
> +    def test_solr_request_error(self, mock_response, core, common_params):
Yes, sounds good

2024-08-23 12:57 UTC, marinak-ebi requested changes

2024-08-23 21:46 UTC, dpavam commented on impc_api_helper/tests/test_solr_request.py
> +            mock_response.json.return_value = request.param.get("json")
Well spotted. Makes me wonder if I've set up something wrong because this test was passing.

2024-08-23 22:06 UTC, dpavam commented on impc_api_helper/tests/test_solr_request.py
> +        captured_output = io.StringIO()
That's a great idea! I had not used it before, thanks for pointing out.

2024-09-09 13:41 UTC, dpavam commented on impc_api_helper/tests/test_solr_request.py
> +        mock_response.assert_called_once()
Further adjusted the existing check_url_and_params to adapt this idea. Now, it checks all key elements of `solr_request` in a single a compartment and it's reusable.

2024-09-09 14:50 UTC, marinak-ebi approved these changes

2024-09-09 19:44 UTC, merged